# ─────────────── Basic info ───────────────
title: "Jiachao Liu"                # Your name
description: "digital twins"
email: "jiachaol at andrew dot cmu dot edu"
# github_username: "jiachaoliu"
# repository: "jiachaoliu/jiachaoliu.github.io"

# ─────────────── Site settings ───────────────
url: "https://jiachaoliu.github.io"  # do not add trailing /
baseurl: ""                          # leave empty for main user site
remote_theme: "academicpages/academicpages"  # already set by template

# ─────────────── Navigation ───────────────
# (you can add/remove items; these correspond to files in _pages/)
nav_pages:
  - about.md
  - research.md
  - publications.md
  - teaching.md
  - projects.md
  - cv.md

# ─────────────── Appearance ───────────────
# You can adjust these later if you want custom colors
theme_skin: "default"        # try 'dark', 'classic', or 'minimal'
paginate: 5                  # posts per page

# ─────────────── Social links ───────────────
orcid_username: "0000-0002-XXXX-XXXX"
linkedin_username: "jiachao-liu"
google_scholar_id: "AbCdEfGHIjk"     # part after ?user= in your Scholar URL
twitter_username: "jiachaoliu"
